name: Changes Made on Old Python Code

on:
  push:
    paths:
      - 'plot_log_matrix_multiplication.py' # path for the updated Python file

jobs:
  compare_changes:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository to access its contents
    - name: Checkout repository
      uses: actions/checkout@v2
      
    # Optional: Setting up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    # Step 2: Compare the changes between the old version of the file and the new one
    - name: Compare changes with old version
      run: |
        echo "Comparing old_file.py with plot_log_matrix_multiplication.py"
        if [ -f old_file.py ] && [ -f plot_log_matrix_multiplication.py ]; then
          diff old_file.py plot_log_matrix_multiplication.py > changes.log || true
          cat changes.log
        else
          echo "One or both of the files do not exist!"
          exit 1
        fi

    # Step 3: Upload the generated 'changes.log' so it can be downloaded later
    - name: Upload comparison report
      if: success() # Only upload if previous steps succeeded
      uses: actions/upload-artifact@v2
      with:
        name: comparison-report
        path: changes.log
