name: Unit testing with pytest and linting with flake8

on: [push] # when should we run this action

jobs: # what should we do when it is run

  lint: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: flake8 . --exclude=venv

  build:
    runs-on: ubuntu-latest # platform it runs on
    steps:
    - uses: actions/checkout@v2 # checkout your code
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' # specify python version
    - name: Install dependencies # which libraries do we need for testing
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # they should be listed in this file
    - name: Test with pytest
      run: pytest corrected_code.py
