name: Unit testing with pytest for matrix multiplication

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: List directory contents  # Debugging step to see contents
      run: ls -al
    - name: Test with pytest
      run: pytest test_matrix_multiplication.py
