name: Matrix Multiplication Test, Plot, and Log

on:
  push:
    branches:
      - main

jobs:
  test-and-plot:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: List directory contents  # Debugging step to see contents
      run: ls -al
    - name: Run matrix multiplication tests, generate plot, and write to log
      run: pytest matrix_multiplications.py

    - name: Upload plot and log as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: results
        path: |
          multiplication_methods_comparison.png
          execution_times.log
